
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package test.smit.xroad.persons_register;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-27T18:28:04.612+02:00
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "persons_register",
                      portName = "persons_registerSOAP",
                      targetNamespace = "http://xroad.smit.test/persons_register/",
                      wsdlLocation = "classpath:persons_register.wsdl",
                      endpointInterface = "test.smit.xroad.persons_register.PersonsRegister")

public class Persons_RegisterSOAPImpl implements PersonsRegister {

    private static final Logger LOG = Logger.getLogger(Persons_RegisterSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see test.smit.xroad.persons_register.PersonsRegister#personList(java.lang.String in)*
     */
    public java.lang.String personList(java.lang.String in) {
        LOG.info("Executing operation personList");
        System.out.println(in);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
