package test.smit.xroad.persons_register;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-27T18:28:04.619+02:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://xroad.smit.test/persons_register/", name = "persons_register")
@XmlSeeAlso({eu.x_road.xsd.identifiers.ObjectFactory.class, eu.x_road.xsd.xroad.ObjectFactory.class, ObjectFactory.class})
public interface PersonsRegister {

    @WebMethod(action = "http://xroad.smit.test/persons_register/personList")
    @RequestWrapper(localName = "personList", targetNamespace = "http://xroad.smit.test/persons_register/", className = "test.smit.xroad.persons_register.PersonList")
    @ResponseWrapper(localName = "personListResponse", targetNamespace = "http://xroad.smit.test/persons_register/", className = "test.smit.xroad.persons_register.PersonListResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String personList(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
