package test.smit.xroad.persons_register;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-27T18:28:04.634+02:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "persons_register",
                  wsdlLocation = "classpath:persons_register.wsdl",
                  targetNamespace = "http://xroad.smit.test/persons_register/")
public class PersonsRegister_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xroad.smit.test/persons_register/", "persons_register");
    public final static QName PersonsRegisterSOAP = new QName("http://xroad.smit.test/persons_register/", "persons_registerSOAP");
    static {
        URL url = PersonsRegister_Service.class.getClassLoader().getResource("persons_register.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PersonsRegister_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:persons_register.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonsRegister_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonsRegister_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonsRegister_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PersonsRegister_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonsRegister_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonsRegister_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonsRegister
     */
    @WebEndpoint(name = "persons_registerSOAP")
    public PersonsRegister getPersonsRegisterSOAP() {
        return super.getPort(PersonsRegisterSOAP, PersonsRegister.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonsRegister
     */
    @WebEndpoint(name = "persons_registerSOAP")
    public PersonsRegister getPersonsRegisterSOAP(WebServiceFeature... features) {
        return super.getPort(PersonsRegisterSOAP, PersonsRegister.class, features);
    }

}
